AWSTemplateFormatVersion: 2010-09-09
Description: |
  This project converts numbers into Roman numerals
Parameters:
  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64"
  KeyName:
    Description: Enter the name of your Key Pair for SSH connections
    Type: AWS::EC2::KeyPair::KeyName
    Default: firstkey
Resources:
  RomanNumeralsProject:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro
      KeyName: firstkey
      SecurityGroups: 
        - !Ref RomanProjectSG
      Tags: 
        - Key: Name
          Value: !Sub Web Server of ${AWS::StackName} Stack
      UserData:
        Fn::Base64: !Sub |
            #! /bin/bash
            dnf update -y
            dnf install python -y
            dnf install pip -y
            pip install Flask
            cd /home/ec2-user
            wget -P templates https://raw.githubusercontent.com/turangozukara/Roman-Nums-Converter/main/templates/index.html
            wget -P templates https://raw.githubusercontent.com/turangozukara/Roman-Nums-Converter/main/templates/result.html
            wget https://raw.githubusercontent.com/turangozukara/Roman-Nums-Converter/main/roman-numerals-converter-app.py
            python3 roman-numerals-converter-app.py
  RomanProjectSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "This security group enables 22, 80 and 8080 ports." # Required
      GroupName: "Roman-Project-SG"
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
Outputs:
  WebSiteURL:
    Description: This output gives the URL of EC2
    Value: !Sub 
      - http://${PublicAddress}
      - PublicAddress: !GetAtt RomanNumeralsProject.PublicDnsName